apiVersion: apps/v1
kind: Deployment
metadata:
  name: react01-back
  labels:
    app: react01-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react01-back
  template:
    metadata:
      labels:
        app: react01-back
    spec:
      containers:
      - name: react01-back
        image: hennighausen/react01-max-dev-backend:v1 
        ports:
        - containerPort: 4000
