apiVersion: apps/v1
kind: Deployment
metadata:
  name: react03-front
  labels:
    app: react03-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react03-front
  template:
    metadata:
      labels:
        app: react03-front
    spec:
      containers:
      - name: react03-front
        image: hennighausen/react01-max-dev-frontend:v1
        ports:
        - containerPort: 3000
