apiVersion: apps/v1
kind: Deployment
metadata:
  name: react03-back
  labels:
    app: react03-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react03-back
  template:
    metadata:
      labels:
        app: react03-back
    spec:
      containers:
      - name: react03-back
        image: hennighausen/react01-max-dev-backend:v1
        ports:
        - containerPort: 4000
