kind: Service
apiVersion: v1
metadata:
  name: react03-front
spec:
  type: NodePort
  selector:
    app: react03-front
  ports:
    - port: 3000
      targetPort: 3000
#      nodePort: 31000
      nodePort: 30101
      nodePort: 30102
